blank_issues_enabled: false
contact_links:
  - name: "Paycrest Dev Community"
    url: "https://t.me/+Stx-wLOdj49iNDM0"
    about: "Please ask and answer questions here."
  - name: "Paycrest Security Bug Bounty"
    url: "engineering@paycrest.io"
    about: "Please report security vulnerabilities here."